server {
    listen 80;
    server_name _;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    location /__PFX__/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /__PFX__/index.html;
    }

    location = /__PFX__ {
        return 301 /__PFX__/;
    }

    location /__PFX__/v1/ {
        proxy_pass http://api:4000/v1/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Cookie $http_cookie;
        client_max_body_size 2m;
    }
}
